apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: auth/service-account.json
            - name: TYPEORM_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_CONNECTION
                  name: docker-ormconfig-env
            - name: TYPEORM_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_DATABASE
                  name: docker-ormconfig-env
            - name: TYPEORM_ENTITIES
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_ENTITIES
                  name: docker-ormconfig-env
            - name: TYPEORM_ENTITIES_DIR
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_ENTITIES_DIR
                  name: docker-ormconfig-env
            - name: TYPEORM_HOST
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_HOST
                  name: docker-ormconfig-env
            - name: TYPEORM_LOGGING
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_LOGGING
                  name: docker-ormconfig-env
            - name: TYPEORM_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_PASSWORD
                  name: docker-ormconfig-env
            - name: TYPEORM_PORT
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_PORT
                  name: docker-ormconfig-env
            - name: TYPEORM_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_SYNCHRONIZE
                  name: docker-ormconfig-env
            - name: TYPEORM_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_USERNAME
                  name: docker-ormconfig-env
          image: kassaapje-backend:latest
          name: backend
          ports:
            - containerPort: 8888
          resources: {}
          volumeMounts:
            - mountPath: /usr/app/auth/service-account.json
              name: backend-claim0
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
status: {}
