version: '3.4'

services:
  backend:
    image: kassaapje-backend:latest
    build: .
    ports:
      - 8888:8888
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=auth/service-account.json
    env_file:
      - docker.ormconfig.env
    volumes:
      - ./server/auth/service-account.json:/usr/app/auth/service-account.json
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6.2
    env_file:
      - .env
    ports:
      - 3307:3306
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080
    depends_on:
      - mariadb

volumes:
  database:
