# adminer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: kassaapje # Change to your own namespace!
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kassaapje-adminer
  template:
    metadata:
      labels:
        app: kassaapje-adminer
    spec:
      containers:
        - image: adminer
          name: adminer-container
          ports:
          - containerPort: 8080 # The interal port of the app
            name: 8080tcp
            protocol: TCP
      nodeName: bousson-karel # Change the name of your node!
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  namespace: kassaapje
spec:
  selector:
    app: kassaapje-adminer
  ports:
    - name: 30299tcp
      nodePort: 30299
      port: 9999
      protocol: TCP
      targetPort: 8080
  type: NodePort