apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: kassaapje
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.6.2
          name: mariadb-container
          ports:
            - containerPort: 3306
          envFrom:
          - configMapRef:
              name: env-variables
          - secretRef:
              name: env-secrets
      nodeName: bousson-karel
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: kassaapje
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
  - name: mariadb-port
    port: 3307
    protocol: TCP
    targetPort: 3306