apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
type: Opaque
data:
  TYPEORM_CONNECTION: mysql
  TYPEORM_HOST: mariadb
  TYPEORM_PORT: 3306
  TYPEORM_USERNAME: root
  TYPEORM_PASSWORD: stronger_password
  TYPEORM_DATABASE: kassaapje
  TYPEORM_SYNCHRONIZE: true
  TYPEORM_LOGGING: false
  TYPEORM_ENTITIES: /usr/app/entity/**/*.js
  TYPEORM_ENTITIES_DIR: /usr/app/entity