apiVersion: v1
kind: ConfigMap
metadata:
  name: typeorm-variables
data:
  TYPEORM_CONNECTION: mysql
  TYPEORM_HOST: mariadb
  TYPEORM_PORT: 3306
  TYPEORM_DATABASE: kassaapje
  TYPEORM_SYNCHRONIZE: true
  TYPEORM_LOGGING: false
  TYPEORM_ENTITIES: /usr/app/entity/**/*.js
  TYPEORM_ENTITIES_DIR: /usr/app/entity